<a href="https://colab.research.google.com/github/nvj1d/GANs_with_python/blob/main/Conv2DTranspose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

In [3]:
# define input data
X = asarray([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [5]:
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [6]:
# define model
model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
# summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose (Conv2DTra  (None, 4, 4, 1)          2         
 nspose)                                                         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
# define weights that they do nothing
weights = [asarray([[[[1]]]]), asarray([0])]
print(weights)

[array([[[[1]]]]), array([0])]


In [9]:
# store the weights in the model
model.set_weights(weights)

In [10]:
# make a prediction with the model
yhat = model.predict(X)

1/1 [==============================] - 0s 343ms/step


In [11]:
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]
