In [1]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

In [7]:
# define input data
X = asarray([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [8]:
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [9]:
# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
# summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 up_sampling2d (UpSampling2D  (None, 4, 4, 1)          0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [10]:
# make a prediction with the model
yhat = model.predict(X)
print(yhat)

1/1 [==============================] - 0s 110ms/step
[[[[1.]
   [1.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [4.]
   [4.]]]]


In [11]:
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
